version: '3.5'

services:

  yesplz-frontend:
    container_name: yesplz-frontend
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - '443:443'

    network_mode: "host"
    volumes:
       - type: bind
         source: /home/sjcho/yesplz/media
         target: /srv/www/imgs
         readonly: true
       - type: bind
         source: /home/sjcho/certs
         target: /etc/nginx/certs
         readonly: true

